layout_spectrum: 0.3423179359037872
typography_spectrum: 0.9127914090303354
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.17244469782521968
  lightness: 0.4138013501705989
  saturation: 0.6741644096508217
  rhythmicContrast: 0.39561127076985886
github: true
author:
  name: Netthandelsportalen
  email: post@netthandelsportalen.no
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2fabd7eb-68d5-4f55-b991-6275d9aaf536.png
name: 'Netthanedels Portalen '
url: 'https://cloudportalen.link/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: main site
    url: 'https://www.netthandelsportalen.no:444/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f718f7f8-6895-4cb1-963c-96f92befad1d.png
title: Netthandelsportalen
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/aec10a03-fcfe-45b7-9bc5-d5204fe99f46.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/aec10a03-fcfe-45b7-9bc5-d5204fe99f46.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Nettbutikk, Overv√•kning, Cloud service'
purpose:
  - type: contact
    url: 'mailto:post@netthandelsportalen.no'
    label: Kontakt oss
  - type: external
    url: 'https://www.netthandelsportalen.no:444/'
    label: netthandelsportalen.no
